title: flyingtext
description: flyingtext blog
url: https://flyingtext.github.io
baseurl: ""  # 사용자 사이트면 빈 문자열

theme: null
remote_theme: "mmistakes/minimal-mistakes@latest"

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
minimal_mistakes_skin: "default"  # "dark", "neon" 등 변경 가능
search: true

# 네비게이션
include: ["_pages"]